### ISSUE TITLE
Deployment segítése

### ISSUE THREAD

**Issue by Kniightt** [BME-MIT-IET/Kollegak-iet-2019#1]
Jó lenne ha a projekt futtatásához a csapat egy egységes környezetet használna.
Az Android Studio beépített emulátora helyett érdemes lenne egy gyorsabb szoftvert használni,
pl.: Genymotion, vagy Bluestacks.
Az egységes környezet érdekében célszerű lenne a használni kívánt virtuális gép képfájlját exportálni, majd a futtatáshoz mindenkinek azt felhasználni.

**Comment by Kniightt** [comment]
Kapcsolódó commitok: [Link to OVA file](https://github.com/BME-MIT-IET/Kollegak-iet-2019/commit/a3ac8ee367f8399f00bac050c277ecd8bd1378f5), [Deployment images](https://github.com/BME-MIT-IET/Kollegak-iet-2019/commit/e81fed2896f36cf5e3d5e230e61df52c5bc80d4d)

**Comment by Kniightt** [comment]
Feladat elvégezve. Ellenőrzés kellene.

**Comment by inakasoysauce** [comment]
Rendben van. Működik.
