### ISSUE TITLE
Bugok javítása #2

### ISSUE THREAD

**Issue by labor1234** [BME-MIT-IET/Kollegak-iet-2019#3]
1.  BigDecimal.valueOf() használata new BigDecimal helyett

2. @NonNull annotáció kihagyása, mert nem hajtódik végre az if ág így soha

3. SimpleDateFormat('YYYY') helyett SimpleDateFormat("yyyy") használata

4. Ellenőrzés, hogy a price változó nem null és csak utána hivatkozás rá

5.  BigDecimal.valueOf() használata new BigDecimal helyett egy másik fáljban

**Comment by labor1234** [comment]
Megoldások:

1.  BigDecimal.valueOf() használata new BigDecimal helyett

BigDecimal result = new BigDecimal(expression.evaluate());
----->
BigDecimal result =BigDecimal.valueOf(expression.evaluate()); 

2. @NonNull annotáció kihagyása, mert nem hajtódik végre az if ág így soha

 public long getSplitCount(@NonNull String transactionUID){....}
------>
 public long getSplitCount(String transactionUID){....}

3. SimpleDateFormat('YYYY') helyett SimpleDateFormat("yyyy") használata

    private DateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd", Locale.US);
------>
    private DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.US);

4. Ellenőrzés, hogy a price változó nem null és csak utána hivatkozás rá

---->  if(price!=null){
            price.setSource(Price.SOURCE_USER);
            PricesDbAdapter.getInstance().addRecord(price);
        }

5.  BigDecimal.valueOf() használata new BigDecimal helyett egy másik fáljban

     return new BigDecimal(expression.evaluate());
-------->
      return BigDecimal.valueOf(expression.evaluate());

**Comment by bitmakk** [comment]
travis javítása: A travisnek nincs hozzáférése a gradlew fájlhoz
megoldás: .travis.yml fájlban telepítés előtt chmod a gradlew fájlra

**Comment by labor1234** [comment]
Kapcsolódó Pull Request : #4

**Comment by inakasoysauce** [comment]
Rendben
