### ISSUE TITLE
UI tesztek készítése

### ISSUE THREAD

**Issue by labor1234** [BME-MIT-IET/Kollegak-iet-2019#5]
UI tesztek készítése Espressoval

**Comment by labor1234** [comment]
A_WizardTest-
Első megnyitáskor beállítások megadása.

B_Test1-
Próbaadatok felvétele, fizetés és hitel.

CheckTest-
Adatokfelvétel helyességének leellenőrzése.

D_ReportTest-
Kördiagrammok grafikonok vizsgálata.

HelpTest-
Help menüpont tesztelése.

K_SettingTest-
Jelszó beállítása

L_ScheduleTest-
Schedule létrehozása egy új elemre majd lementése a telefonra.

**Comment by inakasoysauce** [comment]
Kódlefedettség készítése:
    - app.gradle -> android {
                                            buildTypes {
                                               debug {
                                                     testCoverageEnabled true
                                                     ...
                                                     }
                                               }
                                            }
   - app: createBetaDebugCoverageReport
   - app/src/build/reports/coverage/beta/debug/index.html

**Comment by labor1234** [comment]
L_ManageBooksTest-Új Book létrehozása
