### ISSUE TITLE
Unit tesztek készítése

### ISSUE THREAD

**Issue by bitmakk** [BME-MIT-IET/Kollegak-iet-2019#6]
Tesztek kódlefedettségét növelni lehetne

**Comment by bitmakk** [comment]
Kiinduló állapot: metódusok: 28,3%, osztályok: 19,1%

**Comment by bitmakk** [comment]
code coverage engedélyezése
https://github.com/BME-MIT-IET/Kollegak-iet-2019/commit/d1c8443f145b2a72ee9166ee7ce44a56899bc44a

első unit teszt: Exporter classhoz
https://github.com/BME-MIT-IET/Kollegak-iet-2019/commit/0387b20b23e14f69c0478078c731bd46feb81145

**Comment by Kniightt** [comment]
Kész.
